### ISSUE TITLE
老哥 你怎么做到把环境文件 打包到项目中的.

### ISSUE THREAD

**Issue by pyxin** [Chekoo/django-blog#1]
如题  刚刚创建项目 文件中的bin文件夹怎么弄出来的. 我在没有联网了服务器上部署 不知道怎么这么把环境搞好

**Comment by Chekoo** [comment]
bin文件夹是用Virtualenv生成虚拟环境后自动产生的。

**Comment by Chekoo** [comment]
如果在Windows系统下的话，Virtualenv是生成Scripts这个文件夹。Linux下Virtualenv是生成bin文件夹。
这个项目是照着这个教程做下来的。https://www.zmrenwu.com/post/3/，你可以看一下。

**Comment by Chekoo** [comment]
啊,我也是ubuntu,我是先创建了虚拟环境，然后直接在虚拟环境的文件夹里创建django项目,所以就直接在当前文件夹。我这个里面，blogenv是虚拟环境，blogproject才是项目。

**Comment by pyxin** [comment]
为啥 我直接创建环境就跑隐藏目录......

**Comment by Chekoo** [comment]
这。。我也不知道了，再Google看看吧。
