### ISSUE TITLE
关于日期归档

### ISSUE THREAD

**Issue by pyxin** [Chekoo/django-blog#2]
我的模型类中有定义
`
class Post(BaseModel): # 一个基类
    created_time =models.DateTimeField('创建时间',` default=timezone.now)
    date = models.DateField('日期统计用')
`
我在视图中
Post.objects.filter(created_time__year=year, created_time__month=month)这样取总是空的list 
通过 shell 中取也是空的为啥你的就可以 . 我实在没办法了就加了一个字段date

**Comment by pyxin** [comment]
感谢你的回复  我的模型类和你的一样. 请问你的 views.py中165行注释部分能正确执行么?

**Comment by Chekoo** [comment]
恩，可以正确执行。

**Comment by pyxin** [comment]
终于解决了 

问题是我的mysql没有加载时区 命令行执行
```
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql
```
